config/routes.rb
SampleApp::Application.routes.draw do
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/survey/',     to:   "surveys#index",   via: 'get'
  match '/survey/',     to:   "surveys#update",  via: 'patch'
  match '/survey/',     to:   "surveys#create",  via: 'post'
  match '/survey/results', to: "surveys#result",   via: 'get'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="content"><%= feed_item.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_stats_page.html.erb
<% if @user_surveys.present? %>
    <ol class="micropost">
        <% @user_surveys.each do |user_survey| %>
            <li id="<%= user_survey.id %>" class="stats">
                <div class="stat_section">
                    <b>Q)&nbsp;<%= user_survey.question %> </b>
                    <table class="table table-bordered table-stripped">
                        <thead>
                            <tr> 
                                <th>OPTIONS</th>
                                <th>COUNT</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><%= user_survey.option_a%></td>
                                <td><%= user_survey.option_a_count%></td>
                            </tr>
                            <tr>
                                <td><%= user_survey.option_b%></td>
                                <td><%= user_survey.option_b_count%></td>
                            </tr>
                            <tr>
                                <td><%= user_survey.option_c%></td>
                                <td><%= user_survey.option_c_count%></td>
                            </tr>
                            <tr>
                                <td><%= user_survey.option_d%></td>
                                <td><%= user_survey.option_d_count%></td>
                            </tr>
                            <tr>
                                <td>TOTAL #USERS SUBMITTED SURVEY </td>
                                <td><%= user_survey.answer_count%></td>
                            </tr>
                        <tbody>
                    </table>
                    <div class="btn btn-primary" onclick="chart(<%=user_survey.id%>, <%=user_survey.option_a_count%>,<%=user_survey.option_b_count%>,<%=user_survey.option_c_count%>,<%=user_survey.option_d_count%>)">Chart</div>
                    <div class="graph" id="chart<%=user_survey.id %>">
                    </div>
                </div>
            </li>
            <hr/>
        <% end %>
    </ol>
<% else %>
    <span>
        <b> User don't have any survey present</b>
    </span>
 <% end %>

app/views/shared/_survey_feed.html.erb
<% if @survey_items.present? %>
    <ol class="microposts">
      <%= render partial: 'shared/survey_item', collection: @survey_items %>
  </ol>
  <% will_paginate @survey_items %>
<% end %>

app/views/shared/_survey_form.html.erb
<%= form_for(@survey, :url => { :action => :create }, remote: true) do |f| %>
    
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.label :question, "Question:", :style => "float:left" %>
    <%= f.text_area :question, placeholder: "Enter Your Qestion Here", :style => "float:left" %>
    
    <%= f.label :option_a, "Option A ->", :style => "float:left" %><br/>
    <%= f.text_field :option_a, :style => "float:left" %>

    <%= f.label :option_b, "Option B ->", :style => "float:left" %><br/>
    <%= f.text_field :option_b, :style => "float:left" %>

    <%= f.label :option_c, "Option C ->", :style => "float:left" %><br/>
    <%= f.text_field :option_c, :style => "float:left" %>

    <%= f.label :option_d, "Option D ->", :style => "float:left" %>
    <%= f.text_field :option_d, :style => "float:left" %> <br/>
<br/>
    <%= f.submit "Submit!", class: "btn btn-primary", :style => "float:left" %>
<% end %>

app/views/shared/_survey_item.html.erb
<li id="<%= survey_item.id %>">
  <%= link_to gravatar_for(survey_item.user), survey_item.user %>
    <span class="user">
      <%= link_to survey_item.user.name, survey_item.user %>
    </span>
    
    <%= form_for(survey_item, html: { method: :patch}, remote: true) do |f| %>
      <span class="content">
        <b>Q)&nbsp;<%= survey_item.question %> </b>
      </span>
      
      <span class="span8 options">
        <%= render 'shared/error_messages', object: f.object %>
        <%= f.hidden_field :survey_id, :value => survey_item.id %>
        
        <% if answered(survey_item) %>
          <%= f.check_box :option_a, {:id => "option_a#{survey_item.id}", :style => "float:left;"}, true, false %>
          <%= f.label :option_a, "#{survey_item.option_a}".html_safe, {:for => "option_a#{survey_item.id}", :style => "float:left"} %> <br/>
          
          <%= f.check_box :option_b, {:id => "option_b#{survey_item.id}", :style => "float:left;"}, true, false %>
          <%= f.label :option_b, "#{survey_item.option_b}".html_safe, {:for => "option_b#{survey_item.id}", :style => "float:left"} %> <br/>

          <%= f.check_box :option_c, {:id => "option_c#{survey_item.id}", :style => "float:left;"}, true, false %>
          <%= f.label :option_c, "#{survey_item.option_c}".html_safe, {:for => "option_c#{survey_item.id}", :style => "float:left"} %> <br/>

          <%= f.check_box :option_d, {:id => "option_d#{survey_item.id}", :style => "float:left;"}, true, false %>
          <%= f.label :option_d, "#{survey_item.option_d}".html_safe, {:for => "option_d#{survey_item.id}", :style => "float:left"} %> <br/>
          
          <%= f.submit "Submit!", class: "btn btn-primary" %>

        <% else %>
          <span> You have already taken this survey </span>
        <% end %>
      </span>
      <span class="timestamp">
        Posted <%= time_ago_in_words(survey_item.created_at) %> ago.
      </span>
    <% end %>
</li>

app/views/shared/_survey_page_user_info.html.erb
<div id="profile">
  <%= link_to gravatar_for(current_user, size: 52), current_user %>
  <h1>
      <%= current_user.name %>
  </h1>
  <span>
    <%= link_to "view profile", current_user %>
  </span>
  <span>
    <%= link_to "#{current_user.surveys.count} surveys", survey_results_path %>
  </span>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>